#!/usr/bin/env bash

set -x

: ${THISDIR:=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)}
: ${PROJECT:=$(dirname $THISDIR)}

rm -f ${THISDIR}/hal/api.so && python ${THISDIR}/setup.py build_ext --inplace

set +x